version: 0.2

env:
  variables:
    TZ: "Asia/Seoul"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - export JAVA_17_HOME="/usr/lib/jvm/java-17-amazon-corretto.aarch64"
      - export JDK_17_HOME="/usr/lib/jvm/java-17-amazon-corretto.aarch64"
      - export JRE_17_HOME="/usr/lib/jvm/java-17-amazon-corretto.aarch64"
      - export JAVA_HOME="$JAVA_17_HOME"
      - export JRE_HOME="$JRE_17_HOME"
      - export JDK_HOME="$JDK_17_HOME"
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - yum install java-17-amazon-corretto-devel -y
      - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.aarch64/bin/java
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  commands:
    - cd ./service/build/libs
  files:
    - 'backend-service-minuting-0.0.1.jar'
