version: 0.2

env:
  variables:
    TZ: "Asia/Seoul"
    JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto/"
phases:
  install:
    commands:
      - apt-get update; apt-get install -y java-17-amazon-corretto-jdk
      - update-alternatives --auto javac
      - update-alternatives --auto java
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ${CODEBUILD_SRC_DIR}/(...) && ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
artifacts:
  files:
    - '**/*'
